version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    command: ['mysqld', '--sql_mode=']
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      #- ./dbconfig:/etc/mysql
      - ./db:/var/lib/mysql
    restart: always

  php:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
    restart: always

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8096:8080
    restart: always
